# Generated by Django 4.1.4 on 2023-08-16 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Materiel',
            fields=[
                ('id_materiel', models.AutoField(primary_key=True, serialize=False)),
                ('refrence_materiel', models.CharField(blank=True, max_length=11, null=True)),
                ('numero_interne_materiel', models.CharField(max_length=100)),
                ('designation_materiel', models.CharField(max_length=100)),
                ('certificat', models.CharField(max_length=100, null=True)),
                ('date_emission', models.DateField()),
                ('etat_materiel', models.CharField(choices=[('actif', 'Actif'), ('inactif', 'Inactif')], max_length=7)),
                ('observation_materiel', models.TextField(blank=True)),
            ],
        ),
    ]
