# Generated by Django 4.1.4 on 2023-08-22 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materiels', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='materiel',
            old_name='refrence_materiel',
            new_name='reference_materiel',
        ),
    ]
