# Generated by Django 4.1.4 on 2023-08-29 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiels', '0002_rename_refrence_materiel_materiel_reference_materiel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materiel',
            name='etat_materiel',
            field=models.CharField(choices=[('Actif', 'Actif'), ('Inactif', 'Inactif')], max_length=7),
        ),
    ]
