# Generated by Django 4.1.4 on 2023-12-04 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiels', '0003_alter_materiel_etat_materiel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materiel',
            name='numero_interne_materiel',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
