# Generated by Django 4.1.4 on 2023-08-16 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('materiels', '0001_initial'),
        ('documents', '0001_initial'),
        ('normes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id_instrument', models.AutoField(primary_key=True, serialize=False)),
                ('reference_instrument', models.CharField(blank=True, max_length=11, null=True)),
                ('numero_interne_instrument', models.CharField(max_length=100)),
                ('designation_instrument', models.CharField(max_length=100)),
                ('mois_etalonnage', models.CharField(choices=[('Janvier', 'Janvier'), ('Février', 'Février'), ('Mars', 'Mars'), ('Avril', 'Avril'), ('Mai', 'Mai'), ('Juin', 'Juin'), ('Juilet', 'Juillet'), ('Août', 'Août'), ('Septembre', 'Septembre'), ('Octobre', 'Octobre'), ('Novembre', 'Novembre'), ('Décembre', 'Décembre')], max_length=10)),
                ('etat_instrument', models.CharField(choices=[('actif', 'Actif'), ('inactif', 'Inactif')], max_length=7)),
                ('frequence_controle', models.IntegerField()),
                ('critere_acceptation', models.DecimalField(decimal_places=2, max_digits=5)),
                ('observation_instrument', models.TextField(blank=True)),
                ('documents_instrument', models.ManyToManyField(blank=True, to='documents.document')),
                ('materiels_instrument', models.ManyToManyField(blank=True, to='materiels.materiel')),
                ('normes_instrument', models.ManyToManyField(blank=True, to='normes.norme')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id_service', models.AutoField(primary_key=True, serialize=False)),
                ('numero_service', models.IntegerField()),
                ('designation_service', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id_type', models.AutoField(primary_key=True, serialize=False)),
                ('designation_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='OperationEtalonnage',
            fields=[
                ('id_operation', models.AutoField(primary_key=True, serialize=False)),
                ('numero_operation', models.PositiveIntegerField(default=1)),
                ('resultat_operation', models.CharField(choices=[('conforme', 'Conforme'), ('reforme', 'Reforme')], max_length=8)),
                ('numero_pv', models.CharField(max_length=100)),
                ('date_etalonnage', models.DateTimeField(auto_now_add=True)),
                ('observation_instrument', models.TextField(blank=True)),
                ('instrument_operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instruments.instrument')),
            ],
        ),
        migrations.AddField(
            model_name='instrument',
            name='service_instrument',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='instruments.service'),
        ),
        migrations.AddField(
            model_name='instrument',
            name='type_instrument',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='instruments.type'),
        ),
    ]
