# Generated by Django 4.1.4 on 2023-08-22 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrument',
            name='etat_instrument',
            field=models.CharField(choices=[('Actif', 'Actif'), ('Inactif', 'Inactif')], max_length=7),
        ),
    ]
