# Generated by Django 4.1.4 on 2023-08-29 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0002_alter_instrument_etat_instrument'),
    ]

    operations = [
        migrations.RenameField(
            model_name='operationetalonnage',
            old_name='observation_instrument',
            new_name='observation_etalonnage',
        ),
    ]
