# Generated by Django 4.1.4 on 2023-08-29 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0003_rename_observation_instrument_operationetalonnage_observation_etalonnage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operationetalonnage',
            name='observation_etalonnage',
            field=models.CharField(choices=[('conforme', 'Conforme'), ('reforme', 'Reforme')], max_length=8),
        ),
        migrations.AlterField(
            model_name='operationetalonnage',
            name='resultat_operation',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
