# Generated by Django 4.1.4 on 2023-09-02 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0005_alter_operationetalonnage_observation_etalonnage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operationetalonnage',
            name='numero_operation',
        ),
    ]
