# Generated by Django 4.1.4 on 2023-12-04 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0006_remove_operationetalonnage_numero_operation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrument',
            name='numero_interne_instrument',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
