# Generated by Django 4.1.4 on 2023-09-10 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profils', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Custom',
        ),
    ]
